service: docuassist-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-central-1'}
  memorySize: 256
  timeout: 30
  logRetentionInDays: 14
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
    metrics: true
  logs: #3rd dep
    restApi:
      level: INFO
      fullExecutionData: true
      

  environment:
    ORG_TABLE: Orgs-${self:provider.stage}
    USERS_TABLE: Users-${self:provider.stage}
    COGNITO_USER_POOL_ID: !Ref UserPool
    COGNITO_CLIENT_ID: !Ref UserPoolClient
    CONVERSATIONS_TABLE: Conversations-${self:provider.stage}

  # Add base IAM role statements that all functions will inherit
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: 
            - arn:aws:logs:${self:provider.region}:${aws:accountId}:*
        - Effect: Allow
          Action:
            - cognito-idp:AdminCreateUser
            - cognito-idp:AdminGetUser
            - cognito-idp:AdminInitiateAuth
            - cognito-idp:AdminRespondToAuthChallenge
            - cognito-idp:AdminSetUserPassword
            - cognito-idp:AdminUpdateUserAttributes
            - cognito-idp:AdminDeleteUser
            - cognito-idp:GlobalSignOut
          Resource: 
            - !GetAtt UserPool.Arn
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:BatchGetItem
            - dynamodb:BatchWriteItem
          Resource:
            # Table permissions
            - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/Users-${self:provider.stage}
            - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/Orgs-${self:provider.stage}
            - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/Conversations-${self:provider.stage}
            - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/Messages-${self:provider.stage}
            - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/Files-${self:provider.stage}
            - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/FileConversationMapping-${self:provider.stage}
            # Index permissions
            - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/Users-${self:provider.stage}/index/*
            - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/Messages-${self:provider.stage}/index/*
            - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/Files-${self:provider.stage}/index/*

functions:
  getCurrentUser:
    handler: src/handlers/auth.getCurrentUser
    events:
      - http:
          path: /auth/me
          method: get
          cors:
            origin: '*'
            headers: ${self:custom.corsHeaders}
            allowCredentials: true

  createUser:
    handler: src/handlers/auth.createUser
    events:
      - http:
          path: /auth/users
          method: post
          cors:
            origin: '*'
            headers: ${self:custom.corsHeaders}
            allowCredentials: true

  refreshToken:
    handler: src/handlers/auth.refreshToken
    events:
      - http:
          path: /auth/token/refresh
          method: post
          cors:
            origin: '*'
            headers: ${self:custom.corsHeaders}
            allowCredentials: true

  validateToken:
    handler: src/handlers/auth.validateToken
    events:
      - http:
          path: /auth/token/validate
          method: post
          cors:
            origin: '*'
            headers: ${self:custom.corsHeaders}
            allowCredentials: true

  loginUser:
    handler: src/handlers/auth.loginUser
    events:
      - http:
          path: /auth/login
          method: post
          cors:
            origin: '*'
            headers: ${self:custom.corsHeaders}
            allowCredentials: true

  signup:
    handler: src/handlers/auth.signup
    events:
      - http:
          path: /auth/signup
          method: post
          cors:
            origin: '*'
            headers: ${self:custom.corsHeaders}
            allowCredentials: true

  signupConfirmed:
    handler: src/handlers/auth.signupConfirmed
    events:
      - http:
          path: /auth/signup-confirmed
          method: post
          cors:
            origin: '*'
            headers: ${self:custom.corsHeaders}
            allowCredentials: true

  createConversation:
    handler: src/handlers/conversations.createConversation
    events:
      - http:
          path: /conversations
          method: post
          cors:
            origin: '*'
            headers: ${self:custom.corsHeaders}
            allowCredentials: true

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  userPoolArn: !GetAtt UserPool.Arn
  esbuild:
    bundle: true
    minify: true
    target: 'node20'
    platform: 'node'
    sourcemap: true
    exclude:
      - aws-sdk  # Ensure aws-sdk is excluded
  corsHeaders:
    - Accept
    - Content-Type
    - Content-Length
    - Authorization
    - X-Amz-Date
    - X-Api-Key
    - X-Amz-Security-Token
    - X-Amz-User-Agent
    - X-Access-Token

resources:
  - ${file(serverless/resources/cognito.yml)}
  - ${file(serverless/resources/dynamodb-tables.yml)}
  - ${file(serverless/resources/api-gateway.yml)} #2nd dep