# resources/dynamodb-tables.yml
Resources:
  OrgsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Orgs-${self:provider.stage}
      AttributeDefinitions:
        - AttributeName: orgId
          AttributeType: S
      KeySchema:
        - AttributeName: orgId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Users-${self:provider.stage}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId   # ULID
          AttributeType: S
        - AttributeName: orgId
          AttributeType: S
        - AttributeName: user_id_ref  # Add this for the Cognito ID
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: orgId
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: UserIdRefIndex
          KeySchema:
            - AttributeName: user_id_ref
              KeyType: HASH
          Projection:
            ProjectionType: ALL
  ConversationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Conversations-${self:provider.stage}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: conversationId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: conversationId
          KeyType: RANGE

  AllMessagesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: AllMessages-${self:provider.stage}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: conversationId
          AttributeType: S
        - AttributeName: messageId
          AttributeType: S
      KeySchema:
        - AttributeName: conversationId
          KeyType: HASH
        - AttributeName: messageId
          KeyType: RANGE
      